name: ms_undraw
description: Updated UnDraw library. These illustrations are designed by Katerina Limpitsouni.
version: 2.2.0+7
repository: https://github.com/Marcus-Software/ms_undraw

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ">=0.13.1 <1.0.0"
  http: ">=0.12.0+2 <1.0.0"

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.0.0
  build_test: ^0.10.3

flutter:
